// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "syncTag": string;
      "folder": string;
      "deviceToken": string;
      "syncMode": string;
      "syncInterval": number;
      "deleteOnUnsync": boolean;
      "safeMode": boolean;
      "convertDocx": boolean;
      "syncNotes": boolean;
    };
  }
}
